### ISSUE TITLE
Hardcoded IPFS_EXEC path not always correct

### ISSUE THREAD

**Issue by noffle** [ipfs/node-ipfsd-ctl#13]
The current version of `ipfsd-ctl` hardcodes the following path:

`var IPFS_EXEC = __dirname + '/node_modules/.bin/ipfs'

This works fine when the module is at the root (e.g. git clone this repo and run `npm test`), but doesn't work when `ipfsd-ctl` is used as a dependency. In this `IPFS_EXEC` evaluates to 

`node_modules/ipfsd-ctl/node_modules/.bin/ipfs`

however, if the root module depends on `go-ipfs` the proper path to the binary will actually be `node_modules/.bin/ipfs`.

I'm preparing a PR that will use `require-resolve` to get the proper module path and look into its `/bin` directory.

**Comment by jbenet** [comment]
Ah, because npm might put `go-ipfs` elsewhere, right?

**Comment by noffle** [comment]
Right. It could end up at `node_modules/go-ipfs/bin/ipfs` or `node_modules/ipfsd-ctl/node_modules/go-ipfs/ifs`, for example.
