### ISSUE TITLE
Double Kill

### ISSUE THREAD

**Issue by travisperson** [ipfs/node-ipfsd-ctl#3]
`go-ipfs` is notorious about not shutting down after receiving a kill signal, I think we should probably put a timeout that will trigger the send kill signal to force it to shutdown after a timeout.

**Comment by jbenet** [comment]
> `go-ipfs` is notorious about not shutting down after receiving a kill signal

am saddened by this. we should get our shit together there.

**Comment by jbenet** [comment]
> I think we should probably put a timeout that will trigger the send kill signal to force it to shutdown after a timeout.

safe call for now.

**Comment by travisperson** [comment]
> am saddened by this. we should get our shit together there.

I might try to sit down and see if I can make any headway through this issue this week. It's primarily after heave use, so it might be a context that is lagging behind.

**Comment by diasdavid** [comment]
This should not be a problem anymore with subcomandante? Right?

**Comment by jbenet** [comment]
@diasdavid i believe so. but not sure
