### ISSUE TITLE
test multiaddr grabbing from stdout

### ISSUE THREAD

**Issue by krl** [ipfs/node-ipfsd-ctl#8]
We are grabbing multiaddrs to connect to from stdout, make sure this is not broken somewhere in a redesign.

**Comment by jbenet** [comment]
yeah :+1:

**Comment by jbenet** [comment]
btw, this is why it's important to _not break userspace_.

cc everyone working on ipfs

**Comment by travisperson** [comment]
Make a sharness test :smile:

**Comment by jbenet** [comment]
yep
